### ISSUE TITLE
How to find my_host value.

### ISSUE THREAD

**Issue by santhosh12992** [PerfectoCode/Templates#1]
I know my username and my password values. Can someone please help me to find "my_host" value.

**Comment by daniel4x** [comment]
Hey @santhosh12992 , 
my_host regards to your perfecto lab host's name.
In most of the code samples it's a **prefix** of the URL ,for example:

> my_host = MyCompany
> MyCompany.perfectomobile.com  

Hence, if you are a Perfecto's client and don't sure about your host name you may want contact our support team: 
https://www.perfectomobile.com/ni/support/open-new-support-case 

Otherwise, you may want check our developers portal for more information about how to setup your own tests with Perfecto: 
http://developers.perfectomobile.com/ 

I hope you found it helpful, 
Daniel.

**Comment by santhosh12992** [comment]
Thanks for the help daniel. I have created a separate ticket to get my_host details.

**Comment by daniel4x** [comment]
Great :) , closing this issue. 
If something goes wrong, don't hesitate open a new issue.
